### PR TITLE
Output Buffers, Romanian Translation & Removing User Level

### PR DESCRIPTION
**Pull request by thenbrent**
Hey Eric, 

As promised here's a pull request of my changes. It brings output buffers for login_form etc. hooks, adds Romanian translation & removes user level for adding menus as its deprecated. 

You can view the details of changes I've made by looking at the commit log on github: https://github.com/thenbrent/simplemodal-login/commits/master

The first commit is a little funky as I didn't realise simplemodal login was on github, so created a new repo from the WordPress.org version with commit fcef8df3534bb857480e2bd88555237750d5c3dd.

However, when I merged your repo in commit bb3a6fdd7ec87c27857b95c560611b8f3217b3c3 I used it to override any wordpress.org differences.

Let me know if you've got any questions. GitHub will give you instructions for merging, but if s**t happens, as it can do with git, let me know and I'll help out. 

Brent

### CODE REVIEW

**Comment by ericmmartin** [comment]
You'll have to forgive me for having no idea how this all works ;)

I commited 1.0.3 changes earlier and just went through your output buffering changes and added them in my repo...I think. I'm going to test and make sure everything is working well and probably put them in the WP repo early next week.

Thanks!

**Comment by thenbrent** [comment]
I put my previous email into a blog post here: http://iblog.thereforei.am/2010/11/24/my-git-workflow/

Scroll down to "Multiplayer Git" for a slightly more detailed guide/explanation of what to do with this. :)

**Comment by ericmmartin** [comment]
Thanks again for putting those tips together. I'll give it a try and let you know how it goes ;)

**Comment by ericmmartin** [comment]
So, I've created the branch and pulled you changes. If I only wanted to bring in selective changes, what do I do? Do I just do the merge and then make changes or is there another way?

**Comment by thenbrent** [comment]
You can cherry pick changes by commit. 

These two sites help with understanding cherry picking: 
http://nathanhoad.net/how-to-cherry-pick-changes-with-git
http://www.kernel.org/pub/software/scm/git/docs/git-cherry-pick.html

I'm not aware of any way in git to be more specific than commit. 

A friend also pointed me to GitBox the other day. It might be helpful if you're on mac: http://gitboxapp.com/

**Pull request merged**
